---
- hosts: all
  become: true
  tasks:
  - name: "Install Updates"
    dnf:
      name: "*"
      state: latest
  - name: "Reboot"
    reboot:
  - name: "Install Cockpit"
    dnf:
      name:
        - cockpit
        - cockpit-storaged
        - cockpit-storaged
      state: present
  - name: "Install Nvidia"
    dnf:
      name: akmod-nvidia
      state: present
  - name: "Install Updates"
    dnf:
      name: "*"
      state: present
  - name: "VSCode"
    dnf:
      name: https://code.visualstudio.com/sha/download?build=stable&os=linux-rpm-x64 
      state: present
  - name: "Install Resilio"
    dnf:
      # Update this with a new link from https://help.resilio.com/hc/en-us/articles/206178924-Installing-Sync-package-on-Linux
      name: https://download-cdn.resilio.com/2.7.3.1381/RPM/resilio-sync-2.7.3.1381-1.x86_64.rpm
      state: present
  - name: "Change Resilio Unit file"
    lineinfile:
      path: /usr/lib/systemd/user/resilio-sync.service 
      regex: '^WantedBy=multi-user\.target'
      line: 'WantedBy=default.target'
  - name: "Disable and stop Resilio from running as a system daemon"
    script: ./resilio-disable.sh
  - name: "Add VirtualBox Repo"
    yum_repository:
      name: "VirtualBox"
      baseurl: "http://download.virtualbox.org/virtualbox/rpm/fedora/$releasever/$basearch"
      gpgkey: "https://www.virtualbox.org/download/oracle_vbox_2016.asc"
  - name: "Install VirtualBox"
    dnf:
      name: "Virtualbox-7.0"
      state: present
  - name: "Add Current user to vboxusers group"
    user:
      # change user to match your configuration
      name: command
      groups: vboxusers
      append: yes
  - name: "Install Ansible"
    dnf:
      name:
        - ansible
        - ansible-lint
        - ansible-doc
      state: present
  - name: "install Chrome"
    flatpak:
      name: com.google.Chrome
      state: present
  - name: "Intall Discord"
    flatpak:
      name: com.discordapp.Discord
      state: present
  - name: "Install Keybase"
    dnf:
      name: https://prerelease.keybase.io/keybase_amd64.rpm
      state: present
  - name: "Final Update check"
    dnf:
      name: "*"
      state: latest
  - name: "Final Reboot"
    reboot:
