---
- hosts: all
  become: yes
  tasks:
  - name: "Install Updates"
    dnf:
      name: "*"
      state: latest
  - name: "Reboot"
    reboot:
  - name: "Install RPM Fusion"
    dnf:
      name:
        - 'https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-31.noarch.rpm'
        - 'https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-31.noarch.rpm'
      state: present
  - name: "Install Cockpit"
    dnf:
      name:
        - cockpit
        - cockpit-storaged
        - cockpit-storaged
      state: latest
  - name: "Install KeepassXC"
    dnf:
      name: "keepassxc"
      state: latest
  - name: "Install Nvidia Dependencies"
    dnf:
      name:
        - kernel-devel
        - kernel-headers
        - gcc
        - make
        - dkms
        - acpid
        - libglvnd-glx
        - libglvnd-opengl
        - libglvnd-devel
        - pkgconfig
      state: latest
    # - name: "Install Nvidia"
    #   dnf:
    #     name:
    #       - akmod-nvidia
    #       - xorg-x11-drv-nvidia-cuda
    #     state: latest
    # - name: "Install Updates"
    #   dnf:
    #     name: "*"
    #     state: latest
  - name: "Install VSCode"
    dnf:
      name: https://go.microsoft.com/fwlink/?LinkID=760867
      state: present
  - name: "Install Atom"
    dnf:
      name: https://atom.io/download/rpm
      state: present